# for loop on a string

s1 = "Python"

for char in s1:
    print(char)

# for loop on a dictionary

student1 = {'roll':101, 'name':'John', 'percent':87.5}

print("Printing the keys:")
for i in student1:
    print(i) # 'i' stores the keys of the dict - one by one

print(student1['roll'])

print("Printing the values:")
for i in student1:
    print(student1[i])

print("Printing both key-value pairs:")
for i in student1:
    print(i, student1[i])

# for loop on dict.keys(), dict.values() and dict.items()

keys = student1.keys()
print(keys)

for key in student1.keys():
    print(key)

for value in student1.values():
    print(value)

items = student1.items()
print(items)

for item in student1.items():
    print(item, type(item))

# for loops on set

set1 = {7, 'hi', "Python", 6.4, True}

for i in set1:
    print(i)

###########

"""
range() => used to generate a sequence of integers

Syntax:
range(start, stop, step)
start => starting integer from where we want to generate the sequence
stop => last (ending) integer where we want to stop generating the sequence (stop is excluded)
step => increment/decrement
"""

r1 = range(10, 15, 1) # generates 10, 11, 12, 13, 14
print(r1)

"""
To see the value generated by the range():
1. typecast the range output to list/tuple, ...
2. run a for loop on the range output
"""

l1 = list(r1)
print(l1)

for i in range(5, 10, 1):
    print(i)

for i in range(10, 20, 2):
    print(i)


for i in range(10, 25, 3):
    print(i)

print("Hello")
for i in range(10, 1, 1):
    print(i)

for i in range(10, 1, -1):
    print(i)

for i in range(-5, -10, -1):
    print(i)

# generate integers -> 10, 15, 20, ....., 45, 50
for i in range(10, 55, 5):
    print(i)


# generate the countdown from 10 to 0
print("Countdown starts.....")
for i in range(10, -1, -1):
    print(i)


# default values for range

for i in range(1, 5): # step = 1 by default
    print(i)

# default value for start = 0
for i in range(5): # start=0, step=1 by default
    print(i)

"""
for i in range():
    print(i)
stop is required
"""

"""
for i in range(10, 20, 0):
    print(i)
step cannot be 0
"""

""""
for i in range(1.5, 4.5, 0.5):
    print(i)

range() cannot be used with floats, ONLY integers
"""